### ISSUE TITLE
Imported data needs validation

### ISSUE THREAD

**Issue by wesrupert** [wesrupert/dnd-character-quickref#11]
Imported data that doesn't match the expected format fails silently.

**Comment by frozenfoxx** [comment]
Is this something we can do with TypeScript easily or should be use something like a compiled Go binary we bundle with it? I'm unfamiliar with how to do this in TypeScript and would definitely like to learn. I found an article that talks a lot about several different forms we could use [here](https://blog.logrocket.com/dynamic-type-validation-in-typescript/).
